const cloud = require('wx-server-sdk')

// https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-server-api/database/collection.where.html
cloud.init({
    env: cloud.DYNAMIC_CURRENT_ENV
})

const lawMap = {
    'civil-litigation-explanation': { '一、管辖': { value: '一、管辖', start: 1, end: 42 },
        '二、回避': { value: '二、回避', start: 43, end: 49 },
        '三、诉讼参加人': { value: '三、诉讼参加人', start: 50, end: 89 },
        '四、证据': { value: '四、证据', start: 90, end: 124 },
        '五、期间和送达': { value: '五、期间和送达', start: 125, end: 141 },
        '六、调解': { value: '六、调解', start: 142, end: 151 },
        '七、保全和先予执行': { value: '七、保全和先予执行', start: 152, end: 173 },
        '八、对妨害民事诉讼的强制措施': { value: '八、对妨害民事诉讼的强制措施', start: 174, end: 193 },
        '九、诉讼费用': { value: '九、诉讼费用', start: 194, end: 207 },
        '十、第一审普通程序': { value: '十、第一审普通程序', start: 208, end: 155 },
        '十一、简易程序': { value: '十一、简易程序', start: 256, end: 270 },
        '十二、简易程序中的小额诉讼': { value: '十二、简易程序中的小额诉讼', start: 271, end: 283 },
        '十三、公益诉讼': { value: '十三、公益诉讼', start: 284, end: 291 },
        '十四、第三人撤销之诉': { value: '十四、第三人撤销之诉', start: 292, end: 303 },
        '十五、执行异议之诉': { value: '十五、执行异议之诉', start: 304, end: 316 },
        '十六、第二审程序': { value: '十六、第二审程序', start: 317, end: 342 },
        '十七、特别程序': { value: '十七、特别程序', start: 343, end: 374 },
        '十八、审判监督程序': { value: '十八、审判监督程序', start: 375, end: 426 },
        '十九、督促程序': { value: '十九、督促程序', start: 427, end: 443 },
        '二十、公示催告程序': { value: '二十、公示催告程序', start: 444, end: 461 },
        '二十一、执行程序': { value: '二十一、执行程序', start: 462, end: 521 },
        '二十二、涉外民事诉讼程序的特别规定': { value: '二十二、涉外民事诉讼程序的特别规定', start: 522, end: 551 },
        '二十三、附则': { value: '二十三、附则', start: 552, end: 552 } },
    'criminal-litigation-explanation': { '第一章 管辖': { value: '第一章 管辖', start: 1, end: 26 },
        '第二章 回避': { value: '第二章 回避', start: 27, end: 39 },
        '第三章 辩护与代理': { value: '第三章 辩护与代理', start: 40, end: 68 },
        '第四章 证据': { value: '第四章 证据', start: 69, end: 146 },
        '第一节 一般规定': { value: '第一节 一般规定', start: 546, end: 562 },
        '第二节 物证、书证的审查与认定': { value: '第二节 物证、书证的审查与认定', start: 82, end: 86 },
        '第三节 证人证言、被害人陈述的审查与认定': { value: '第三节 证人证言、被害人陈述的审查与认定', start: 87, end: 92 },
        '第四节 被告人供述和辩解的审查与认定': { value: '第四节 被告人供述和辩解的审查与认定', start: 93, end: 96 },
        '第五节 鉴定意见的审查与认定': { value: '第五节 鉴定意见的审查与认定', start: 97, end: 101 },
        '第六节 勘验、检查、辨认、侦查实验等笔录的审查与认定':
            { value: '第六节 勘验、检查、辨认、侦查实验等笔录的审查与认定', start: 102, end: 107 },
        '第七节 视听资料、电子数据的审查与认定': { value: '第七节 视听资料、电子数据的审查与认定', start: 108, end: 115 },
        '第八节 技术调查、侦查证据的审查与认定': { value: '第八节 技术调查、侦查证据的审查与认定', start: 116, end: 122 },
        '第九节 非法证据排除': { value: '第九节 非法证据排除', start: 123, end: 138 },
        '第十节 证据的综合审查与运用': { value: '第十节 证据的综合审查与运用', start: 139, end: 146 },
        '第五章 强制措施': { value: '第五章 强制措施', start: 147, end: 174 },
        '第六章 附带民事诉讼': { value: '第六章 附带民事诉讼', start: 175, end: 201 },
        '第七章 期间、送达、审理期限': { value: '第七章 期间、送达、审理期限', start: 202, end: 211 },
        '第八章 审判组织': { value: '第八章 审判组织', start: 212, end: 217 },
        '第九章 公诉案件第一审普通程序': { value: '第九章 公诉案件第一审普通程序', start: 218, end: 315 },
        '第一节 审查受理与庭前准备': { value: '第一节 审查受理与庭前准备', start: 218, end: 225 },
        '第二节 庭前会议与庭审衔接': { value: '第二节 庭前会议与庭审衔接', start: 226, end: 233 },
        '第三节 宣布开庭与法庭调查': { value: '第三节 宣布开庭与法庭调查', start: 234, end: 279 },
        '第四节 法庭辩论与最后陈述': { value: '第四节 法庭辩论与最后陈述', start: 280, end: 290 },
        '第五节 评议案件与宣告判决': { value: '第五节 评议案件与宣告判决', start: 291, end: 304 },
        '第六节 法庭纪律与其他规定': { value: '第六节 法庭纪律与其他规定', start: 305, end: 315 },
        '第十章 自诉案件第一审程序': { value: '第十章 自诉案件第一审程序', start: 316, end: 334 },
        '第十一章 单位犯罪案件的审理': { value: '第十一章 单位犯罪案件的审理', start: 335, end: 346 },
        '第十二章 认罪认罚案件的审理': { value: '第十二章 认罪认罚案件的审理', start: 347, end: 358 },
        '第十三章 简易程序': { value: '第十三章 简易程序', start: 359, end: 368 },
        '第十四章 速裁程序': { value: '第十四章 速裁程序', start: 369, end: 377 },
        '第十五章 第二审程序': { value: '第十五章 第二审程序', start: 378, end: 413 },
        '第十六章 在法定刑以下判处刑罚和特殊假释的核准': { value: '第十六章 在法定刑以下判处刑罚和特殊假释的核准', start: 414, end: 422 },
        '第十七章 死刑复核程序': { value: '第十七章 死刑复核程序', start: 423, end: 436 },
        '第十八章 涉案财物处理': { value: '第十八章 涉案财物处理', start: 437, end: 450 },
        '第十九章 审判监督程序': { value: '第十九章 审判监督程序', start: 451, end: 474 },
        '第二十章 涉外刑事案件的审理和刑事司法协助': { value: '第二十章 涉外刑事案件的审理和刑事司法协助', start: 475, end: 496 },
        '第一节 涉外刑事案件的审理': { value: '第一节 涉外刑事案件的审理', start: 475, end: 490 },
        '第二节 刑事司法协助': { value: '第二节 刑事司法协助', start: 491, end: 496 },
        '第二十一章 执行程序': { value: '第二十一章 执行程序', start: 497, end: 545 },
        '第一节 死刑的执行': { value: '第一节 死刑的执行', start: 497, end: 510 },
        '第二节 死刑缓期执行、无期徒刑、有期徒刑、拘役的交付执行':
            { value: '第二节 死刑缓期执行、无期徒刑、有期徒刑、拘役的交付执行', start: 511, end: 518 },
        '第三节 管制、缓刑、剥夺政治权利的交付执行': { value: '第三节 管制、缓刑、剥夺政治权利的交付执行', start: 519, end: 520 },
        '第四节 刑事裁判涉财产部分和附带民事裁判的执行': { value: '第四节 刑事裁判涉财产部分和附带民事裁判的执行', start: 521, end: 532 },
        '第五节 减刑、假释案件的审理': { value: '第五节 减刑、假释案件的审理', start: 533, end: 541 },
        '第六节 缓刑、假释的撤销': { value: '第六节 缓刑、假释的撤销', start: 542, end: 545 },
        '第二十二章 未成年人刑事案件诉讼程序': { value: '第二十二章 未成年人刑事案件诉讼程序', start: 546, end: 586 },
        '第二节 开庭准备': { value: '第二节 开庭准备', start: 563, end: 570 },
        '第三节 审判': { value: '第三节 审判', start: 571, end: 579 },
        '第四节 执行': { value: '第四节 执行', start: 580, end: 586 },
        '第二十三章 当事人和解的公诉案件诉讼程序': { value: '第二十三章 当事人和解的公诉案件诉讼程序', start: 587, end: 597 },
        '第二十四章 缺席审判程序': { value: '第二十四章 缺席审判程序', start: 598, end: 608 },
        '第二十五章 犯罪嫌疑人、被告人逃匿、死亡案件违法所得的没收程序':
            { value: '第二十五章 犯罪嫌疑人、被告人逃匿、死亡案件违法所得的没收程序',
                start: 609,
                end: 629 },
        '第二十六章 依法不负刑事责任的精神病人的强制医疗程序':
            { value: '第二十六章 依法不负刑事责任的精神病人的强制医疗程序', start: 630, end: 649 },
        '第二十七章 附则': { value: '第二十七章 附则', start: 650, end: 655 } },
    'road-safe-violation-handling': { '第一章 总则': { value: '第一章 总则', start: 1, end: 3 },
        '第二章 管辖': { value: '第二章 管辖', start: 4, end: 6 },
        '第三章 调查取证': { value: '第三章 调查取证', start: 7, end: 23 },
        '第一节 一般规定': { value: '第一节 一般规定', start: 7, end: 14 },
        '第二节 交通技术监控': { value: '第二节 交通技术监控', start: 15, end: 23 },
        '第四章 行政强制措施适用': { value: '第四章 行政强制措施适用', start: 24, end: 41 },
        '第五章 行政处罚': { value: '第五章 行政处罚', start: 42, end: 62 },
        '第一节 行政处罚的决定': { value: '第一节 行政处罚的决定', start: 42, end: 58 },
        '第二节 行政处罚的执行': { value: '第二节 行政处罚的执行', start: 59, end: 62 },
        '第六章 执法监督': { value: '第六章 执法监督', start: 63, end: 66 },
        '第七章 其他规定': { value: '第七章 其他规定', start: 67, end: 76 },
        '第八章 附则': { value: '第八章 附则', start: 77, end: 83 } },
    'police-admin-regulation': {
        '第一章 总则': { start: 1, end: 9 },
        '第二章 管辖': { start: 10, end: 16 },
        '第三章 回避': { start: 17, end: 25 },
        '第四章 证据': { start: 26, end: 34 },
        '第五章 期间与送达': { start: 35, end: 36 },
        '第六章 简易程序和快速办理': { value: '第六章 简易程序和快速办理', start: 37, end: 48 },
        '第一节 简易程序': { start: 37, end: 39 },
        '第二节 快速办理': { start: 40, end: 48 },
        '第七章 调查取证': { value: '第七章 调查取证', start: 49, end: 122 },
        '第一节 一般规定': { start: 198, end: 213 },
        '第二节 受案': { start: 60, end: 65 },
        '第三节 询问': { start: 66, end: 80 },
        '第四节 勘验、检查': { start: 81, end: 86 },
        '第五节 鉴定': { start: 87, end: 100 },
        '第六节 辨认': { start: 101, end: 106 },
        '第七节 证据保全': { start: 107, end: 116 },
        '第八节 办案协作': { start: 117, end: 122 },
        '第八章 听证程序': { value: '第八章 听证程序', start: 123, end: 153 },
        '第二节 听证人员和听证参加人': { start: 127, end: 131 },
        '第三节 听证的告知、申请和受理': { start: 132, end: 136 },
        '第四节 听证的举行': { start: 137, end: 153 },
        '第九章 行政处理决定': { value: '第九章 行政处理决定', start: 154, end: 177 },
        '第一节 行政处罚的适用': { start: 154, end: 164 },
        '第二节 行政处理的决定': { start: 165, end: 177 },
        '第十章 治安调解': { value: '第十章 治安调解', start: 178, end: 186 },
        '第十一章 涉案财物的管理和处理': { value: '第十一章 涉案财物的管理和处理', start: 187, end: 197 },
        '第十二章 执行': { value: '第十二章 执行', start: 198, end: 237 },
        '第二节 罚款的执行': { start: 214, end: 219 },
        '第三节 行政拘留的执行': { start: 220, end: 233 },
        '第四节 其他处理决定的执行': { start: 234, end: 237 },
        '第十三章 涉外行政案件的办理': { value: '第十三章 涉外行政案件的办理', start: 238, end: 257 },
        '第十四章 案件终结': { value: '第十四章 案件终结', start: 258, end: 262 },
        '第十五章 附则': { value: '第十五章 附则', start: 263, end: 266 } },
    'road-safe-regulation':{ '第一章 总则': { value: '第一章 总则', start: 1, end: 3 },
        '第二章 车辆和驾驶人': { value: '第二章 车辆和驾驶人', start: 4, end: 28 },
        '第一节 机动车': { value: '第一节 机动车', start: 4, end: 18 },
        '第二节 机动车驾驶人': { value: '第二节 机动车驾驶人', start: 19, end: 28 },
        '第三章 道路通行条件': { value: '第三章 道路通行条件', start: 29, end: 37 },
        '第四章 道路通行规定': { value: '第四章 道路通行规定', start: 38, end: 85 },
        '第一节 一般规定': { value: '第一节 一般规定', start: 38, end: 43 },
        '第二节 机动车通行规定': { value: '第二节 机动车通行规定', start: 44, end: 67 },
        '第三节 非机动车通行规定': { value: '第三节 非机动车通行规定', start: 68, end: 73 },
        '第四节 行人和乘车人通行规定': { value: '第四节 行人和乘车人通行规定', start: 74, end: 77 },
        '第五节 高速公路的特别规定': { value: '第五节 高速公路的特别规定', start: 78, end: 85 },
        '第五章 交通事故处理': { value: '第五章 交通事故处理', start: 86, end: 97 },
        '第六章 执法监督': { value: '第六章 执法监督', start: 98, end: 101 },
        '第七章 法律责任': { value: '第七章 法律责任', start: 102, end: 110 },
        '第八章 附则': { value: '第八章 附则', start: 111, end: 115 } },
    'road-safe-law': { '第一章 总则': { value: '第一章 总则', start: 1, end: 7 },
        '第二章 车辆和驾驶人': { value: '第二章 车辆和驾驶人', start: 8, end: 24 },
        '第一节 机动车、非机动车': { value: '第一节 机动车、非机动车', start: 8, end: 18 },
        '第二节 机动车驾驶人': { value: '第二节 机动车驾驶人', start: 19, end: 24 },
        '第三章 道路通行条件': { value: '第三章 道路通行条件', start: 25, end: 34 },
        '第四章 道路通行规定': { value: '第四章 道路通行规定', start: 35, end: 69 },
        '第一节 一般规定': { value: '第一节 一般规定', start: 35, end: 41 },
        '第二节 机动车通行规定': { value: '第二节 机动车通行规定', start: 42, end: 56 },
        '第三节 非机动车通行规定': { value: '第三节 非机动车通行规定', start: 57, end: 60 },
        '第四节 行人和乘车人通行规定': { value: '第四节 行人和乘车人通行规定', start: 61, end: 66 },
        '第五节 高速公路的特别规定': { value: '第五节 高速公路的特别规定', start: 67, end: 69 },
        '第五章 交通事故处理': { value: '第五章 交通事故处理', start: 70, end: 77 },
        '第六章 执法监督': { value: '第六章 执法监督', start: 78, end: 86 },
        '第七章 法律责任': { value: '第七章 法律责任', start: 87, end: 118 },
        '第八章 附则': { value: '第八章 附则', start: 119, end: 124 } },
    'public-order-admin-penalty-law': { '第一章 总则': { value: '第一章 总则', start: 1, end: 9 },
        '第二章 处罚的种类和适用': { value: '第二章 处罚的种类和适用', start: 10, end: 22 },
        '第三章 违反治安管理的行为和处罚': { value: '第三章 违反治安管理的行为和处罚', start: 23, end: 76 },
        '第一节 扰乱公共秩序的行为和处罚': { value: '第一节 扰乱公共秩序的行为和处罚', start: 23, end: 29 },
        '第二节 妨害公共安全的行为和处罚': { value: '第二节 妨害公共安全的行为和处罚', start: 30, end: 39 },
        '第三节 侵犯人身权利、财产权利的行为和处罚': { value: '第三节 侵犯人身权利、财产权利的行为和处罚', start: 40, end: 49 },
        '第四节 妨害社会管理的行为和处罚': { value: '第四节 妨害社会管理的行为和处罚', start: 50, end: 76 },
        '第四章 处罚程序': { value: '第四章 处罚程序', start: 77, end: 111 },
        '第一节 调查': { value: '第一节 调查', start: 77, end: 90 },
        '第二节 决定': { value: '第二节 决定', start: 91, end: 102 },
        '第三节 执行': { value: '第三节 执行', start: 103, end: 111 },
        '第五章 执法监督': { value: '第五章 执法监督', start: 112, end: 117 },
        '第六章 附则': { value: '第六章 附则', start: 118, end: 119 } },
    'admin-allow-law': { '第一章 总则': { value: '第一章 总则', start: 1, end: 10 },
        '第二章 行政许可的设定': { value: '第二章 行政许可的设定', start: 11, end: 21 },
        '第三章 行政许可的实施机关': { value: '第三章 行政许可的实施机关', start: 22, end: 28 },
        '第四章 行政许可的实施程序': { value: '第四章 行政许可的实施程序', start: 29, end: 57 },
        '第一节 申请与受理': { value: '第一节 申请与受理', start: 29, end: 33 },
        '第二节 审查与决定': { value: '第二节 审查与决定', start: 34, end: 41 },
        '第三节 期限': { value: '第三节 期限', start: 42, end: 45 },
        '第四节 听证': { value: '第四节 听证', start: 46, end: 48 },
        '第五节 变更与延续': { value: '第五节 变更与延续', start: 49, end: 50 },
        '第六节 特别规定': { value: '第六节 特别规定', start: 51, end: 57 },
        '第五章 行政许可的费用': { value: '第五章 行政许可的费用', start: 58, end: 59 },
        '第六章 监督检查': { value: '第六章 监督检查', start: 60, end: 70 },
        '第七章 法律责任': { value: '第七章 法律责任', start: 71, end: 81 },
        '第八章 附则': { value: '第八章 附则', start: 82, end: 83 } },
    'admin-reconsider-regulation': { '第一章 总则': { value: '第一章 总则', start: 1, end: 4 },
        '第二章 行政复议申请': { value: '第二章 行政复议申请', start: 5, end: 26 },
        '第一节 申请人': { value: '第一节 申请人', start: 5, end: 10 },
        '第二节 被申请人': { value: '第二节 被申请人', start: 11, end: 14 },
        '第三节 行政复议申请期限': { value: '第三节 行政复议申请期限', start: 15, end: 17 },
        '第四节 行政复议申请的提出': { value: '第四节 行政复议申请的提出', start: 18, end: 26 },
        '第三章 行政复议受理': { value: '第三章 行政复议受理', start: 27, end: 31 },
        '第四章 行政复议决定': { value: '第四章 行政复议决定', start: 32, end: 52 },
        '第五章 行政复议指导和监督': { value: '第五章 行政复议指导和监督', start: 53, end: 61 },
        '第六章 法律责任': { value: '第六章 法律责任', start: 62, end: 65 },
        '第七章 附则': { value: '第七章 附则', start: 66, end: 66 } },
    'admin-reconsider-law': { '第一章 总则': { value: '第一章 总则', start: 1, end: 5 },
        '第二章 行政复议范围': { value: '第二章 行政复议范围', start: 6, end: 8 },
        '第三章 行政复议申请': { value: '第三章 行政复议申请', start: 9, end: 16 },
        '第四章 行政复议受理': { value: '第四章 行政复议受理', start: 17, end: 21 },
        '第五章 行政复议决定': { value: '第五章 行政复议决定', start: 22, end: 33 },
        '第六章 法律责任': { value: '第六章 法律责任', start: 34, end: 38 },
        '第七章 附则': { value: '第七章 附则', start: 39, end: 43 } },
    'admin-punish-law': { '第一章 总则': { value: '第一章 总则', start: 1, end: 8 },
        '第二章 行政处罚的种类和设定': { value: '第二章 行政处罚的种类和设定', start: 9, end: 16 },
        '第三章 行政处罚的实施机关': { value: '第三章 行政处罚的实施机关', start: 17, end: 21 },
        '第四章 行政处罚的管辖和适用': { value: '第四章 行政处罚的管辖和适用', start: 22, end: 38 },
        '第五章 行政处罚的决定': { value: '第五章 行政处罚的决定', start: 39, end: 65 },
        '第一节 一般规定': { value: '第一节 一般规定', start: 39, end: 50 },
        '第二节 简易程序': { value: '第二节 简易程序', start: 51, end: 53 },
        '第三节 普通程序': { value: '第三节 普通程序', start: 54, end: 62 },
        '第四节 听证程序': { value: '第四节 听证程序', start: 63, end: 65 },
        '第六章 行政处罚的执行': { value: '第六章 行政处罚的执行', start: 66, end: 75 },
        '第七章 法律责任': { value: '第七章 法律责任', start: 76, end: 83 },
        '第八章 附则': { value: '第八章 附则', start: 84, end: 86 } },
    'admin-force-law':{ '第一章 总则': { value: '第一章 总则', start: 1, end: 8 },
        '第二章 行政强制的种类和设定': { value: '第二章 行政强制的种类和设定', start: 9, end: 15 },
        '第三章 行政强制措施实施程序': { value: '第三章 行政强制措施实施程序', start: 16, end: 33 },
        '第一节 一般规定': { value: '第一节 一般规定', start: 34, end: 44 },
        '第二节 查封、扣押': { value: '第二节 查封、扣押', start: 22, end: 28 },
        '第三节 冻结': { value: '第三节 冻结', start: 29, end: 33 },
        '第四章 行政机关强制执行程序': { value: '第四章 行政机关强制执行程序', start: 34, end: 52 },
        '第二节 金钱给付义务的执行': { value: '第二节 金钱给付义务的执行', start: 45, end: 49 },
        '第三节 代履行': { value: '第三节 代履行', start: 50, end: 52 },
        '第五章 申请人民法院强制执行': { value: '第五章 申请人民法院强制执行', start: 53, end: 60 },
        '第六章 法律责任': { value: '第六章 法律责任', start: 61, end: 68 },
        '第七章 附则': { value: '第七章 附则', start: 69, end: 71 } },
    'admin-litigation-explaination':{ '一、受案范围': { value: '一、受案范围', start: 1, end: 2 },
        '二、管辖': { value: '二、管辖', start: 3, end: 11 },
        '三、诉讼参加人': { value: '三、诉讼参加人', start: 12, end: 33 },
        '四、证据': { value: '四、证据', start: 34, end: 47 },
        '五、期间、送达': { value: '五、期间、送达', start: 48, end: 52 },
        '六、起诉与受理': { value: '六、起诉与受理', start: 53, end: 70 },
        '七、审理与判决': { value: '七、审理与判决', start: 71, end: 127 },
        '八、行政机关负责人出庭应诉': { value: '八、行政机关负责人出庭应诉', start: 128, end: 132 },
        '九、复议机关作共同被告': { value: '九、复议机关作共同被告', start: 133, end: 136 },
        '十、相关民事争议的一并审理': { value: '十、相关民事争议的一并审理', start: 137, end: 144 },
        '十一、规范性文件的一并审查': { value: '十一、规范性文件的一并审查', start: 145, end: 151 },
        '十二、执行': { value: '十二、执行', start: 152, end: 161 },
        '十三、附则': { value: '十三、附则', start: 162, end: 163 } },
    'admin-litigation-law':{ '第一章 总则': { value: '第一章 总则', start: 1, end: 11 },
        '第二章 受案范围': { value: '第二章 受案范围', start: 12, end: 13 },
        '第三章 管辖': { value: '第三章 管辖', start: 14, end: 24 },
        '第四章 诉讼参加人': { value: '第四章 诉讼参加人', start: 25, end: 32 },
        '第五章 证据': { value: '第五章 证据', start: 33, end: 43 },
        '第六章 起诉和受理': { value: '第六章 起诉和受理', start: 44, end: 53 },
        '第七章 审理和判决': { value: '第七章 审理和判决', start: 54, end: 93 },
        '第一节 一般规定': { value: '第一节 一般规定', start: 54, end: 66 },
        '第二节 第一审普通程序': { value: '第二节 第一审普通程序', start: 67, end: 81 },
        '第三节 简易程序': { value: '第三节 简易程序', start: 82, end: 84 },
        '第四节 第二审程序': { value: '第四节 第二审程序', start: 85, end: 89 },
        '第五节 审判监督程序': { value: '第五节 审判监督程序', start: 90, end: 93 },
        '第八章 执行': { value: '第八章 执行', start: 94, end: 97 },
        '第九章 涉外行政诉讼': { value: '第九章 涉外行政诉讼', start: 98, end: 100 },
        '第十章 附则': { value: '第十章 附则', start: 101, end: 103 } },
    'company-law':{ '第一章 总则': { value: '第一章 总则', start: 1, end: 22 },
        '第二章 有限责任公司的设立和组织机构': { value: '第二章 有限责任公司的设立和组织机构', start: 23, end: 70 },
        '第一节 设立': { value: '第一节 设立', start: 76, end: 97 },
        '第二节 组织机构': { value: '第二节 组织机构', start: 36, end: 56 },
        '第三节 一人有限责任公司的特别规定': { value: '第三节 一人有限责任公司的特别规定', start: 57, end: 63 },
        '第四节 国有独资公司的特别规定': { value: '第四节 国有独资公司的特别规定', start: 64, end: 70 },
        '第三章 有限责任公司的股权转让': { value: '第三章 有限责任公司的股权转让', start: 71, end: 75 },
        '第四章 股份有限公司的设立和组织机构': { value: '第四章 股份有限公司的设立和组织机构', start: 76, end: 124 },
        '第二节 股东大会': { value: '第二节 股东大会', start: 98, end: 107 },
        '第三节 董事会、经理': { value: '第三节 董事会、经理', start: 108, end: 116 },
        '第四节 监事会': { value: '第四节 监事会', start: 117, end: 119 },
        '第五节 上市公司组织机构的特别规定': { value: '第五节 上市公司组织机构的特别规定', start: 120, end: 124 },
        '第五章 股份有限公司的股份发行和转让': { value: '第五章 股份有限公司的股份发行和转让', start: 125, end: 145 },
        '第一节 股份发行': { value: '第一节 股份发行', start: 125, end: 136 },
        '第二节 股份转让': { value: '第二节 股份转让"', start: 137, end: 145 },
        '第六章 公司董事、监事、高级管理人员的资格和义务': { value: '第六章 公司董事、监事、高级管理人员的资格和义务', start: 146, end: 152 },
        '第七章 公司债券': { value: '第七章 公司债券', start: 153, end: 162 },
        '第八章 公司财务、会计': { value: '第八章 公司财务、会计', start: 163, end: 171 },
        '第九章 公司合并、分立、增资、减资': { value: '第九章 公司合并、分立、增资、减资', start: 172, end: 179 },
        '第十章 公司解散和清算': { value: '第十章 公司解散和清算', start: 180, end: 190 },
        '第十一章 外国公司的分支机构': { value: '第十一章 外国公司的分支机构', start: 191, end: 197 },
        '第十二章 法律责任': { value: '第十二章 法律责任', start: 198, end: 215 },
        '第十三章 附则': { value: '第十三章 附则', start: 216, end: 218 } },
    'labor-contract-law':{ '第一章 总则': { value: '第一章 总则', start: 1, end: 6 },
        '第二章 劳动合同的订立': { value: '第二章 劳动合同的订立', start: 7, end: 28 },
        '第三章 劳动合同的履行和变更': { value: '第三章 劳动合同的履行和变更', start: 29, end: 35 },
        '第四章 劳动合同的解除和终止': { value: '第四章 劳动合同的解除和终止', start: 36, end: 50 },
        '第五章 特别规定': { value: '第五章 特别规定', start: 51, end: 72 },
        '第一节 集体合同': { value: '第一节 集体合同', start: 51, end: 56 },
        '第二节 劳务派遣': { value: '第二节 劳务派遣', start: 57, end: 67 },
        '第三节 非全日制用工': { value: '第三节 非全日制用工', start: 68, end: 72 },
        '第六章 监督检查': { value: '第六章 监督检查', start: 73, end: 79 },
        '第七章 法律责任': { value: '第七章 法律责任', start: 80, end: 95 },
        '第八章 附则': { value: '第八章 附则', start: 96, end: 98 } },
    'labor-law':{ '第一章 总则': { value: '第一章 总则', start: 1, end: 9 },
        '第二章 促进就业': { value: '第二章 促进就业', start: 10, end: 15 },
        '第三章 劳动合同和集体合同': { value: '第三章 劳动合同和集体合同', start: 16, end: 35 },
        '第四章 工作时间和休息休假': { value: '第四章 工作时间和休息休假', start: 36, end: 45 },
        '第五章 工资': { value: '第五章 工资', start: 46, end: 51 },
        '第六章 劳动安全卫生': { value: '第六章 劳动安全卫生', start: 52, end: 57 },
        '第七章 女职工和未成年工特殊保护': { value: '第七章 女职工和未成年工特殊保护', start: 58, end: 65 },
        '第八章 职业培训': { value: '第八章 职业培训', start: 66, end: 69 },
        '第九章 社会保险和福利': { value: '第九章 社会保险和福利', start: 70, end: 76 },
        '第十章 劳动争议': { value: '第十章 劳动争议', start: 77, end: 84 },
        '第十一章 监督检查': { value: '第十一章 监督检查', start: 85, end: 88 },
        '第十二章 法律责任': { value: '第十二章 法律责任', start: 89, end: 105 },
        '第十三章 附则': { value: '第十三章 附则', start: 106, end: 107 } },
    'anti-drug-law':{ '第一章 总则': { value: '第一章 总则', start: 1, end: 10 },
        '第二章 宣传教育': { value: '第二章 宣传教育', start: 11, end: 18 },
        '第三章 毒品管制': { value: '第三章 毒品管制', start: 19, end: 30 },
        '第四章 戒毒措施': { value: '第四章 戒毒措施', start: 31, end: 52 },
        '第五章 国际合作': { value: '第五章 国际合作', start: 53, end: 58 },
        '第六章 法律责任': { value: '第六章 法律责任', start: 59, end: 70 },
        '第七章 附则': { value: '第七章 附则', start: 71, end: 71 } },
    'anti-terrorism-law':{ '第一章 总则': { value: '第一章 总则', start: 1, end: 11 },
        '第二章 恐怖活动组织和人员的认定': { value: '第二章 恐怖活动组织和人员的认定', start: 12, end: 16 },
        '第三章 安全防范': { value: '第三章 安全防范', start: 17, end: 42 },
        '第四章 情报信息': { value: '第四章 情报信息', start: 43, end: 48 },
        '第五章 调查': { value: '第五章 调查', start: 49, end: 54 },
        '第六章 应对处置': { value: '第六章 应对处置', start: 55, end: 67 },
        '第七章 国际合作': { value: '第七章 国际合作', start: 68, end: 72 },
        '第八章 保障措施': { value: '第八章 保障措施', start: 73, end: 78 },
        '第九章 法律责任': { value: '第九章 法律责任', start: 79, end: 96 },
        '第十章 附则': { value: '第十章 附则', start: 97, end: 97 } },
    'supervision-law':{ '第一章 总则': { value: '第一章 总则', start: 1, end: 6 },
        '第二章 监察机关及其职责': { value: '第二章 监察机关及其职责', start: 7, end: 14 },
        '第三章 监察范围和管辖': { value: '第三章 监察范围和管辖', start: 15, end: 17 },
        '第四章 监察权限': { value: '第四章 监察权限', start: 18, end: 34 },
        '第五章 监察程序': { value: '第五章 监察程序', start: 35, end: 49 },
        '第六章 反腐败国际合作': { value: '第六章 反腐败国际合作', start: 50, end: 52 },
        '第七章 对监察机关和监察人员的监督': { value: '第七章 对监察机关和监察人员的监督', start: 53, end: 61 },
        '第八章 法律责任': { value: '第八章 法律责任', start: 62, end: 67 },
        '第九章 附则': { value: '第九章 附则', start: 68, end: 69 } },
}

exports.main = async (event, context) => {
    console.log(event)
    const db = cloud.database()
    const _ = db.command

    const {type, law, searchValue}= event

    const numberMap = lawMap[law]

    if (!isNaN(parseInt(searchValue))) {
        return await db.collection('other-law')
            .where({
                number: parseInt(searchValue),
                type: law
            }).orderBy('number', 'asc').limit(1000).get()
    }

    if (type === 'category') {
        const {start, end} = numberMap[searchValue]
        return await db.collection('other-law').where({
            number: _.and(_.gte(start),_.lte(end)),
            type: law
        }).orderBy('number', 'asc').limit(1000).get()
    }

    return await db.collection('other-law')
        .where({
            text: db.RegExp({
                regexp: '.*' + searchValue,
                options: 'i',
            }),
            type: law
        }).orderBy('number', 'asc').limit(1000).get()


}
