export const otherLawNameMap = {
  'criminal-litigation-explanation': '(最高法)适用刑事诉讼法的解释',
  'civil-litigation-explanation': '(最高法)适用民事诉讼法的解释',
  'road-safe-violation-handling': '道路交通安全违法行为处理程序规定',
}

export const otherLawAnnounceMap = {
  'criminal-litigation-explanation': '《最高人民法院关于适用〈中华人民共和国刑事诉讼法〉的解释》已于2020年12月7日由最高人民法院审判委员会第1820次会议通过，现予公布，自2021年3月1日起施行。',
  'civil-litigation-explanation': '根据2020年12月23日最高人民法院审判委员会第1823次会议通过的《最高人民法院关于修改〈最高人民法院关于人民法院民事调解工作若干问题的规定〉等十九件民事诉讼类司法解释的决定》修正',
  'road-safe-violation-handling':'《公安部关于修改〈道路交通安全违法行为处理程序规定〉的决定》已经2020年2月12日公安部部务会议通过，现予发布，自2020年5月1日起施行'
}


export const otherLawCategoryMap = {
  'criminal-litigation-explanation': [{"level":1,"value":"第一章 管辖"},{"level":1,"value":"第二章 回避"},{"level":1,"value":"第三章 辩护与代理"},{"level":1,"value":"第四章 证据"},{"level":2,"value":"第一节 一般规定"},{"level":2,"value":"第二节 物证、书证的审查与认定"},{"level":2,"value":"第三节 证人证言、被害人陈述的审查与认定"},{"level":2,"value":"第四节 被告人供述和辩解的审查与认定"},{"level":2,"value":"第五节 鉴定意见的审查与认定"},{"level":2,"value":"第六节 勘验、检查、辨认、侦查实验等笔录的审查与认定"},{"level":2,"value":"第七节 视听资料、电子数据的审查与认定"},{"level":2,"value":"第八节 技术调查、侦查证据的审查与认定"},{"level":2,"value":"第九节 非法证据排除"},{"level":2,"value":"第十节 证据的综合审查与运用"},{"level":1,"value":"第五章 强制措施"},{"level":1,"value":"第六章 附带民事诉讼"},{"level":1,"value":"第七章 期间、送达、审理期限"},{"level":1,"value":"第八章 审判组织"},{"level":1,"value":"第九章 公诉案件第一审普通程序"},{"level":2,"value":"第一节 审查受理与庭前准备"},{"level":2,"value":"第二节 庭前会议与庭审衔接"},{"level":2,"value":"第三节 宣布开庭与法庭调查"},{"level":2,"value":"第四节 法庭辩论与最后陈述"},{"level":2,"value":"第五节 评议案件与宣告判决"},{"level":2,"value":"第六节 法庭纪律与其他规定"},{"level":1,"value":"第十章 自诉案件第一审程序"},{"level":1,"value":"第十一章 单位犯罪案件的审理"},{"level":1,"value":"第十二章 认罪认罚案件的审理"},{"level":1,"value":"第十三章 简易程序"},{"level":1,"value":"第十四章 速裁程序"},{"level":1,"value":"第十五章 第二审程序"},{"level":1,"value":"第十六章 在法定刑以下判处刑罚和特殊假释的核准"},{"level":1,"value":"第十七章 死刑复核程序"},{"level":1,"value":"第十八章 涉案财物处理"},{"level":1,"value":"第十九章 审判监督程序"},{"level":1,"value":"第二十章 涉外刑事案件的审理和刑事司法协助"},{"level":2,"value":"第一节 涉外刑事案件的审理"},{"level":2,"value":"第二节 刑事司法协助"},{"level":1,"value":"第二十一章 执行程序"},{"level":2,"value":"第一节 死刑的执行"},{"level":2,"value":"第二节 死刑缓期执行、无期徒刑、有期徒刑、拘役的交付执行"},{"level":2,"value":"第三节 管制、缓刑、剥夺政治权利的交付执行"},{"level":2,"value":"第四节 刑事裁判涉财产部分和附带民事裁判的执行"},{"level":2,"value":"第五节 减刑、假释案件的审理"},{"level":2,"value":"第六节 缓刑、假释的撤销"},{"level":1,"value":"第二十二章 未成年人刑事案件诉讼程序"},{"level":2,"value":"第一节 一般规定"},{"level":2,"value":"第二节 开庭准备"},{"level":2,"value":"第三节 审判"},{"level":2,"value":"第四节 执行"},{"level":1,"value":"第二十三章 当事人和解的公诉案件诉讼程序"},{"level":1,"value":"第二十四章 缺席审判程序"},{"level":1,"value":"第二十五章 犯罪嫌疑人、被告人逃匿、死亡案件违法所得的没收程序"},{"level":1,"value":"第二十六章 依法不负刑事责任的精神病人的强制医疗程序"},{"level":1,"value":"第二十七章 附则"}],
  'civil-litigation-explanation':[{"level":1,"value":"一、管辖"},{"level":1,"value":"二、回避"},{"level":1,"value":"三、诉讼参加人"},{"level":1,"value":"四、证据"},{"level":1,"value":"五、期间和送达"},{"level":1,"value":"六、调解"},{"level":1,"value":"七、保全和先予执行"},{"level":1,"value":"八、对妨害民事诉讼的强制措施"},{"level":1,"value":"九、诉讼费用"},{"level":1,"value":"十、第一审普通程序"},{"level":1,"value":"十一、简易程序"},{"level":1,"value":"十二、简易程序中的小额诉讼"},{"level":1,"value":"十三、公益诉讼"},{"level":1,"value":"十四、第三人撤销之诉"},{"level":1,"value":"十五、执行异议之诉"},{"level":1,"value":"十六、第二审程序"},{"level":1,"value":"十七、特别程序"},{"level":1,"value":"十八、审判监督程序"},{"level":1,"value":"十九、督促程序"},{"level":1,"value":"二十、公示催告程序"},{"level":1,"value":"二十一、执行程序"},{"level":1,"value":"二十二、涉外民事诉讼程序的特别规定"},{"level":1,"value":"二十三、附则"}],
  'road-safe-violation-handling':[{"level":1,"value":"第一章 总则"},{"level":1,"value":"第二章 管辖"},{"level":1,"value":"第三章 调查取证"},{"level":2,"value":"第一节 一般规定"},{"level":2,"value":"第二节 交通技术监控"},{"level":1,"value":"第四章 行政强制措施适用"},{"level":1,"value":"第五章 行政处罚"},{"level":2,"value":"第一节 行政处罚的决定"},{"level":2,"value":"第二节 行政处罚的执行"},{"level":1,"value":"第六章 执法监督"},{"level":1,"value":"第七章 其他规定"},{"level":1,"value":"第八章 附则"}]
}
